version: '3.1'
services:
  pharmacy-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      PROVIDER_REGULAR_URL: https://api.boostr.cl/pharmacies.json
      PROVIDER_DUTY_URL: https://api.boostr.cl/pharmacies/24h.json
      SYNC_INTERVAL: 15m
      SYNC_TIMEOUT: 10s
